### ISSUE TITLE
Tłumaczenie na język Polski.

### ISSUE THREAD

**Issue by naymapl** [bliskapaczkapl/woocommerce#1]
Witam.

Wtyczka działa ok, ale są z nią pewne problemy.

1. Brak opcji tłumaczenia wtyczki na język polski. Nie ma plików .po, .mo - jedyne tłumaczenie jest możliwe tłumacząc frazy w plikach skryptu co chyba nie jest sensownym rozwiązaniem. Czy planujecie coś w tej kwestii zrobić ??

2. W widoku koszyka nie ma możliwości wybrania opcji przesyłki:
Pokazuje nam się jedynie napis: "Bliskapaczka, od" - mogła by być tutaj jakaś cena minimalna lub tak jak w zamówieniu właściwym opcja wyboru kuriera itp.
 Screen: https://drive.google.com/file/d/1t0IyYQqdXtm-pOpxczLnZPVHcpStz8wg/view?usp=sharing

3. W zamówieniu pokazuje sie nam napis: "Bliskapaczka: 5,66 zł Select delivery point"

To "Select delivery point" powinno być przetłumaczone.

Kolejna sprawa to to że klikająć własnie na "Select delivery point" pojawia się nam mapka ale dużo niżej niż powinna. Najlepiej jakby wogóle pojawiała się jako jakieś okno typu "modal"
Screen:
https://drive.google.com/file/d/1Im5SwOAWONgclM9fDxq4iF7HOC8QcqgJ/view?usp=sharing

Po za tymi szczegółami wszystko działa ok.

**Comment by naymapl** [comment]
Jeszcze od razu dodam że wypadałoby zrobić jakiś CHANGELOG.md

**Comment by mkoszutowski** [comment]
Dziękuję za feedback dotyczący modułu, moduł jest w trakcie aktywnego developmentu i na pewno weźmiemy Państwa uwagi pod uwagę.

Postaram się odpowiedzieć na Pana pytania i uwagi.
Ad 1. W następnych wersjach modułu planujemy dodać tłumaczenia na język polski.
Ad 2. Nie pokazywanie się ceny przy  "Bliskapaczka, od" jest błędem, który na pewno zostanie rozwiązany w następnej wersji modułu. Również plik CHANGELOG.md na pewno się pojawi.

Rozważaliśmy różne sposoby wyświetlania mapki z wyborem punktu dostawy i najprostszym a zarazem najbardziej uniwersalnym - nie zależnym od zewnętrznych bibliotek okazało się wyświetlenie mapki na dole.

**Comment by naymapl** [comment]
Dziękuję za odpowiedź i będę w takim razie z niecierpliwością oczekiwał nowej wersji. Powodzenia w rozwoju wtyczki i usługi bliskapaczka.pl bo pomysł rewelacyjny.

**Comment by naymapl** [comment]
Witam.
Czy udało się dodać polskie tłumaczenia i poprawić inne błędy ?? Z niecierpliwością czekam na informację.

**Comment by mkoszutowski** [comment]
Ostatnie zmiany dodały tłumaczenia modułu na język polski.

**Comment by naymapl** [comment]
Dziękuję za informację. Będę testować polski język.
