### ISSUE TITLE
Problem z wyborem miejsca dostawy.

### ISSUE THREAD

**Issue by naymapl** [bliskapaczkapl/woocommerce#2]
Wybierając jakikolwiek punk dostawy nie zapisuje go w zamówieniu. Pokazuje się ale zaraz znika.
Poniższy gif pokazuje problem:
![2017-12-13 16 43 29](https://user-images.githubusercontent.com/24625283/33947771-96df5cac-e025-11e7-83cc-072218398da3.gif)

W panelu admina tez nie widać żadnych danych:
![zrzut ekranu 2017-12-13 o 16 45 56](https://user-images.githubusercontent.com/24625283/33947793-a1ce9a7e-e025-11e7-9356-7daa3adaab7c.jpg)

Bardzo proszę o szybką reakcję. Miało być tez wyeliminowane kilka poprzednich błędów a od prawie miesiąca nikt nic z tym nie zrobił. Czy ta wtyczka będzie rozwijana na platformę WooCommerce czy lepiej nie korzystać z niej ??

**Comment by mkoszutowski** [comment]
Dziękuję za zgłoszenie problemu. Niestety w testowej wersji WordPress (4.8.2) problem nie występuje albo nie potrafię go powtórzyć. Czy mogę prosić do informację o wersji WordPress i WooCommerce jakiej Pan używa?

**Comment by naymapl** [comment]
WordPress 4.9.1 oraz WooCommerce 3.2.6. Na poprzedniej wersji Woo też było tak samo. Bardzo prosze o weryfikację tych 2 problemów bo z wtyczki nie da sie korzystać w obecnej chwili.

**Comment by sendit-support** [comment]
Wskazany problem został rozwiązany w nowej wersji modułu, która pozostaje do pobrania bezpośrednio ze sklepu wtyczek WordPress.
Zachęcamy do weryfikacji.
