### ISSUE TITLE
Declaration of Bliskapaczka_Shipping_Method::calculate_shipping($package) should be compatible with WC_Shipping_Method::calculate_shipping($package = Array) 

### ISSUE THREAD

**Issue by rkonikpl** [bliskapaczkapl/woocommerce#3]
Problem występuje w PHP 7

Warning: Declaration of Bliskapaczka_Shipping_Method::calculate_shipping($package) should be compatible with WC_Shipping_Method::calculate_shipping($package = Array) in /home/klient.dhosting.pl/republikamy/testrepublikamydla.dkonto.pl/public_html/wp-content/plugins/bliskapaczka-shipping-method/class-bliskapaczka-shipping-method.php on line 33

**Comment by ghost** [comment]
Mam dokładnie ten sam problem, @rkonikpl. Czy udało Ci się go rozwiązać? 

@mkoszutowski ?

**Comment by mkoszutowski** [comment]
@rkonikpl @tutuum Ostatania wersja modułu zawiera już poprawki dla tego błędu.
