### ISSUE TITLE
Brak opcji wyłączenia metody "Bliskapaczka Courier Shipping"

### ISSUE THREAD

**Issue by pkocybik** [bliskapaczkapl/woocommerce#34]
Po zainstalowaniu i aktywacji wtyczki w kokpicie Wordpressa w zakładce > WooCommerce > Ustawienia > Wysyłka pojawiły się dwie nowe zakładki: "Bliskapaczka Courier Shipping" i  "Bliskapaczka Shipping". W pierwszej z nich brakuje opcji włączenia/ wyłączenia danej metody, jeśli chciałbym np. włączyć jedynie opcje wysyłki do punktu, i ukryć opdję wysyłki "do drzwi"na stronie zamówienia.

**Comment by sendit-support** [comment]
Wskazana opcja wyłączenia/włączenia wybranej metody dostawy została dodana do najnowszej wersji wtyczki.

Zachęcamy do pobrania nowej wersji wtyczki bezpośrednio w panelu administracyjnym WordPress.
