### ISSUE TITLE
okno/ popup wyboru mapy

### ISSUE THREAD

**Issue by pkocybik** [bliskapaczkapl/woocommerce#35]
Mapa do wyboru punktu dostawy nie otwiera się w nowym oknie lub popupie, a zamiast tego – "dopisuje" się poniżej formularza zamówienia.

**Comment by cyklosklep-pl-Admin** [comment]
Czy ten problem został rozwiązany?

**Comment by pkocybik** [comment]
Nie wiem, ale patrząc na commity podejrzewam, że niewiele się zmieniło. Przesiadłem się na furgonetka.pl. Bliskapaczka fajnie się zapowiada, ale tą wtyczkę trzeba traktować jako pre-release. bardzo wolno się rozwija, instalacja i aktualizacja jest pozawordpressowa, trzeba ręcznie wszystko wgrywać i uważać przy każdej aktualizacji wordpressa.

**Comment by sendit-support** [comment]
Najnowsza wersja modułu obsługuje mapę w formie okna pop-up. 
Zachęcamy do instalacji nowej wersji wtyczki bezpośrednio z panelu administracyjnego WordPress.
