### ISSUE TITLE
jak to zainstalować?

### ISSUE THREAD

**Issue by duzamrowka** [bliskapaczkapl/woocommerce#5]
Próbowałam przez "Dodaj wtyczkę" i nie działa.
Instrukcje są dla mnie niezrozumiałe. Czym jest katalog domowy wordpressa?
Gdzie jest lista, na której mam sprawdzić czy moduł się pojawia?
Co to znaczy zainstaluj moduł z poziomu panelu admina?
Gdzie znajduje się tajemny klucz API, bo na pewno nie tam gdzie wskazuje opis...

**Comment by mariuszmatlosz** [comment]
Jestem również zdumiony modułem. Przecież nie ma sensu kopiowanie plików composer. Należy jedynie kopiować plugin, ew. language. Z tym, że nic to nie daje. Po skopiowaniu "bliskapaczka-shipping-method" do pluginów, na liście nic się nie pojawia. Nie dziwi mnie to, bo plugin nie ma plików index.php.
Można prosić o przygotowanie paczki, gotowej do wgrania, zamiast kodu do composer-a?
Plik readme jest trochę na odwal, link nigdzie nie prowadzi. Chodzi też o aktywację, a nie instalację z poziomu admina. Będę wdzięczny za jakieś informacje.

**Comment by duzamrowka** [comment]
Udało się Panu zainstalować to, albo uzyskać jakąś pomoc?

**Comment by adamkowalski-pl** [comment]
Ja również nie jestem w stanie zainstalować tej wtyczki. Dostaję taki komunikat:
"Rozpakowywanie paczki…
Instalacja wtyczki…
Paczka nie mogła zostać zainstalowana. Nie znaleziono odpowiednio przygotowanych wtyczek.
Instalacja wtyczki nie powiodła się."

**Comment by psobocinski22** [comment]
W przypadku jakichkolwiek problemów lub niejasności bardzo prosimy kontaktować się z nami na poniższe adresy e-mail:

wsparcie@sendit.pl lub sprzedaz@sendit.pl 

Po otrzymaniu zgłoszenia na jeden z powyższych adresów mailowych z pewnością postaramy się pomóc i problem rozwiązać.

Pozdrawiamy,
Zespół Sendit.

**Comment by duzamrowka** [comment]
> Ja również nie jestem w stanie zainstalować tej wtyczki. Dostaję taki komunikat:
> "Rozpakowywanie paczki…
> Instalacja wtyczki…
> Paczka nie mogła zostać zainstalowana. Nie znaleziono odpowiednio przygotowanych wtyczek.
> Instalacja wtyczki nie powiodła się."

no bo właśnie to taka super wtyczka jest...
Musi Pan ręcznie przekopiować pliki na serwer, część do katalogu głównego a część, która jest w osobnych folderach do analogicznych folderów na serwerze. Aha, i klucza API też nie znajdzie Pan tam gdzie instrukcja wskazuje, trzeba się osobno mailowo prosić. Ale i tak nie polecam, przeszłam do Apaczki, wtyczka działa normalnie, lepiej wygląda i support nie przeciąga wszystkiego tygodniami. Bliska to jakiś żart. I to kiepski.

**Comment by mariuszmatlosz** [comment]
Ale tutaj nie ma żadnego żartu, ani też niejasności. Wrzuciliście Państwo tutaj projekt composera, a wystarczy, że zamieścicie oddzielnie katalog skopiowany z wp-plugins, tak, żebyśmy mogli sobie pobrać. Ja nie używam Composera, więc jest to dla mnie czarna magia. Wiem, że istnieje, ale nie tykałem nigdy. Wyodrębnijcie sam plugin, zamiast całego WP.

**Comment by psobocinski22** [comment]
W przypadku jakichkolwiek problemów lub niejasności bardzo prosimy kontaktować się z nami na poniższe adresy e-mail:

wsparcie@sendit.pl lub sprzedaz@sendit.pl

Po otrzymaniu zgłoszenia na jeden z powyższych adresów mailowych z pewnością postaramy się pomóc i problem rozwiązać.

Działy techniczne nie odpowiadają na zgłoszenia, które pojawiły się w formie komentarzy na GitHub.

Pozdrawiamy,
Zespół Sendit.

**Comment by sendit-support** [comment]
Nowa wersja wtyczki jest już do możliwa do pobrania bezpośrednio z repozytorium WordPress. 
Zapraszamy do pobierania modułu.
