### ISSUE TITLE
ZIP do instalacji

### ISSUE THREAD

**Issue by kantoniak** [bliskapaczkapl/woocommerce#56]
To repozytorium zawiera zdecydowanie więcej plików niż powinno, a instrukcja instalacji każe nadpisywać oryginalne pliki Wordpressa.

Uprzejmie proszę chociaż o udostępnienie ZIPa z release jeśli nie planują Państwo upubliczniać paczki na https://wordpress.org/plugins/

Dla porównania: wtyczki innych firm instaluje się jednym kliknięciem:
* https://wordpress.org/plugins/woo-inpost/
* https://wordpress.org/plugins/apaczka/

**Comment by cyklosklep-pl-Admin** [comment]
Wtyczka powinna być dostępna w repozytorium wtyczek WordPressa.

**Comment by sendit-support** [comment]
Aktualnie wtyczka jest już dostępna w repozytorium WordPressa.
Zachęcamy do weryfikacji: [https://wordpress.org/plugins/bliskapaczka-pl/]

Wtyczkę można pobrać także bezpośrednio ze swojego panelu administracyjnego WordPress.
