### ISSUE TITLE
zamian komunikatów na jeden o błędzie w prztwarzaniu

### ISSUE THREAD

**Issue by slawar11** [bliskapaczkapl/woocommerce#88]
Wtyczka zamienia standardowe komunikaty Wordpressa o braku wypełnienia obligatoryjnych pół lub niezaznaczeniu zgody na regulamin na komunikaty o treści "Wystąpił błąd w prztwarzaniu zamówienia. Jeśli błąd będzie się powtarzał prosimy o kontakt." Absolutnie tak nie może być. Prośba o info kiedy to zostanie poprawione

**Comment by cyklosklep-pl-Admin** [comment]
Czy ten problem został rozwiązany?

**Comment by sendit-support** [comment]
Problem został rozwiązany. Poprawka do niego została dodana do najnowszej wersji wtyczki.
Zachęcamy do weryfikacji.
